import type { Metadata } from "next";
import "./globals.css";
import { GillSans, GillSansBold } from './fonts';

export const metadata: Metadata = {
  title: "Warehouse",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={GillSans.className}>{children}</body>
    </html>
  );
}
